
name: Build on Ubuntu

on:
  pull_request:

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: setup
      run: |
        python3 -m pip install pip -U
        python3 -m pip install black wheel ruff pylint autoflake -U
        python3 -m pip install -r requirements.txt


    - run: ./sh/lint.sh

    - run: ./sh/test.sh
